//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxLineLength.Properties
{
    using System.Globalization;
    using System.Resources;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static ResourceManager? _resourceManager;
        private static CultureInfo? _resourceCulture;

        internal Resources()
        {
        }

        internal static ResourceManager ResourceManager =>
            _resourceManager ??= new ResourceManager(
                "MaxLineLength.Properties.Resources",
                typeof(Resources).Assembly);

        internal static CultureInfo? Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        internal static string CodeCleanupReflowLines =>
            ResourceManager.GetString("CodeCleanupReflowLines", _resourceCulture) ??
            "Reflow lines to configured maximum length";
    }
}
