// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MaxLineLength
{
    internal sealed partial class Vsix
    {
        public const string Id = "MaxLineLength.bbc727b4-1dfb-4d9e-a159-032529f396ed";
        public const string Name = "Max Line Length";
        public const string Description = @"Displays the effective .editorconfig line-length ruler and safely reflows plain text, Markdown paragraphs, C# lists, and supported code comments through Visual Studio's existing format commands.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "editor;.editorconfig;line length;ruler;productivity";
        public const bool IsPreview = false;
    }
}
